/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StreamEvent = ProgressEvent | A2UiEvent | TextEvent | DoneEvent | ErrorEvent;

export interface WireTypes {
  A2uiClientAction?: A2UiClientAction;
  AgentInfo?: AgentInfo;
  ChatRequest?: ChatRequest;
  A2uiEvent?: A2UiEvent;
  DoneEvent?: DoneEvent;
  ErrorEvent?: ErrorEvent;
  ProgressEvent?: ProgressEvent;
  TextEvent?: TextEvent;
  StreamEvent?: StreamEvent;
}
export interface A2UiClientAction {
  /**
   * The name of the action, taken from the component's action.event.name property.
   */
  name: string;
  /**
   * The id of the surface where the event originated.
   */
  surfaceId: string;
  /**
   * The id of the component that triggered the event.
   */
  sourceComponentId: string;
  /**
   * An ISO 8601 timestamp of when the event occurred.
   */
  timestamp: string;
  /**
   * A JSON object containing the key-value pairs from the component's action.event.context, after resolving all data bindings.
   */
  context: {
    [k: string]: unknown;
  };
}
export interface AgentInfo {
  name: string;
  description: string;
  renders_a2ui: boolean;
}
export interface ChatRequest {
  agent: string;
  session_id?: string | null;
  text?: string;
  action?: A2UiClientAction | null;
}
export interface A2UiEvent {
  type: "a2ui";
  messages: {
    [k: string]: unknown;
  }[];
}
export interface DoneEvent {
  type: "done";
  session_id: string | null;
}
export interface ErrorEvent {
  type: "error";
  message: string;
}
export interface ProgressEvent {
  type: "progress";
  tool: string;
}
export interface TextEvent {
  type: "text";
  text: string;
}
